### ISSUE TITLE
“请求的数据或操作在服务器中不存在！获取视频信息失败。”

### ISSUE THREAD

**Issue by ChuandongXie** [yliu7949/KouShare-dl#23]
尝试保存回播视频，出现提示：“请求的数据或操作在服务器中不存在！获取视频信息失败。”

`ks save 512309`

如何处理？

**Comment by yliu7949** [comment]
`ks save [vid]` 命令只能下载正式上线的视频，而 vid 为 512309 的[视频](https://www.koushare.com/video/videodetail/512309)并不存在，因此出现了“请求的数据在服务器中不存在”的错误提示。

请使用 `ks live 512309 --replay` 命令下载还未正式上线的快速回放视频。阅读[这一小节的文档](https://github.com/yliu7949/KouShare-dl#43-%E4%B8%8B%E8%BD%BD%E7%9B%B4%E6%92%AD%E9%97%B4%E5%BF%AB%E9%80%9F%E5%9B%9E%E6%94%BE%E8%A7%86%E9%A2%91)有助于进一步了解该命令。

**Comment by ChuandongXie** [comment]
感谢！已解决。
