### ISSUE TITLE
系列下载时文件命名有bug；以及文件命名的建议

### ISSUE THREAD

**Issue by ZJC-GH** [yliu7949/KouShare-dl#35]
### 一个bug：
下载某个专题系列里面的多个视频文件时，后续文件的名字会变成前面视频名称加上该视频名称的字符串，例如：AA_超清.mp4、AA_超清BB_超清.mp4、AA_超清BB_超清CC_超清.mp4……
版本：KouShare-dl v0.9.1，windows11系统。

### 还有一个建议：
希望下载视频的命名可以利用视频的“报告时间”（与“发布时间”有区别），比如“2023-XX-XX 标题”，或者 “2023-XX-XX 报告人.标题”等等，可以自定义。

**Comment by yliu7949** [comment]
该 bug 在 `v0.9.1` 版本中被引入，现已修复。请稍后尝试最新发布的 `v0.9.2` 版本。
“自定义命名格式”的建议也很不错，但实现这样的功能需要时间，我会考虑在较靠后的版本中实现该功能。
