### ISSUE TITLE
直播录制结束后视频是TS格式的，还要再转成MP4的，并且转码的过程一直提示错误，无法正常转码

### ISSUE THREAD

**Issue by SUP-Eric** [yliu7949/KouShare-dl#37]
我用的是FFBatch 转码的，无法正常转码，有没有好的办法

**Comment by yliu7949** [comment]
可以使用 `FFmpeg` 软件将 `.ts` 文件转换为 `.mp4` 文件。`FFmpeg` 的二进制文件可以在 [FFmpeg-Builds](https://github.com/BtbN/FFmpeg-Builds/releases) 仓库下载。

以 `会议.ts` 文件为例，可以使用下面的命令将其转换为 `会议.mp4` 文件：

```shell
ffmpeg -i "会议.ts" -c copy -map 0:v -map 0:a -bsf:a aac_adtstoasc 会议.mp4
```

调整输出视频质量和重编码视频等用法请参考 `FFmpeg` 的[文档](https://ffmpeg.org/ffmpeg.html)或互联网上的[教程](https://blog.51cto.com/gwj1314/6044797)。
